Repository canonical/indico-operator, pull requests merged in 2023-08, with the labels that each got.

#291 Install Prometheus exporters along with the application
  indico_rock/rockcraft.yaml
  metadata.yaml
  nginx_rock/rockcraft.yaml
  requirements.txt
  src/charm.py
  tests/integration/conftest.py
  tests/integration/test_charm.py
  tests/unit/test_actions.py
  tests/unit/test_base.py
  tests/unit/test_core.py
Labels: Libraries: Out of sync

#298 Use SAML groups identity provider
  docs/reference/plugins.md
  src/charm.py
  tests/unit/test_core.py
Labels: Libraries: Out of sync

#299 Update maintainer to be a URL including scheme so charmhub upload can work
  metadata.yaml
Labels: Libraries: Out of sync

#300 Remove Prometheus exporter references from contribution guide
  docs/how-to/contribute.md
Labels: Libraries: Out of sync

#290 Fix SAML integration tests
  .github/workflows/integration_test.yaml
  .github/workflows/integration_test_with_secrets.yaml
  tests/integration/conftest.py
  tests/integration/test_charm.py
Labels: Libraries: Out of sync

#301 Re-Add CE_ACCEPT_CONTENT to indico env
  src/charm.py
Labels: Libraries: Out of sync, trivial

#304 Add warning to flush Redis cache on redeploy
  docs/explanation/charm-architecture.md
Labels: Libraries: Out of sync, trivial

#305 Add pull request template
  .github/pull_request_template.md
  docs/how-to/contribute.md
  generate-src-docs.sh
  src-docs/charm.py.md
  tox.ini
Labels: Libraries: Out of sync, trivial

#306 Update charm architecture docs
  docs/explanation/charm-architecture.md
  docs/tutorial/getting-started.md
Labels: Libraries: Out of sync, trivial

#310 Upgrade indico to version 3.2.7
  indico_rock/rockcraft.yaml
Labels: Libraries: Out of sync, trivial

#312 Upgrade indico to version 3.2.7
  indico_rock/start-indico.sh
  nginx_rock/rockcraft.yaml
Labels: Libraries: Out of sync, trivial, urgent
