Repository canonical/indico-operator, pull requests merged in 2023-10, with the labels that each got.

#328 Switch to edge runners
  .github/workflows/test.yaml
Labels: Libraries: Out of sync

#331 Upgrade Indico to version 3.2.8
  indico_rock/rockcraft.yaml
  nginx_rock/rockcraft.yaml
Labels: Libraries: Out of sync, trivial

#320 Migrate to new db relation library
  docs/reference/integrations.md
  docs/tutorial/getting-started.md
  lib/charms/data_platform_libs/v0/data_interfaces.py
  metadata.yaml
  pyproject.toml
  requirements.txt
  src-docs/charm.py.md
  src-docs/database_observer.py.md
  src/charm.py
  src/database_observer.py
  tests/integration/conftest.py
  tests/unit/_patched_charm.py
  tests/unit/test_actions.py
  tests/unit/test_base.py
  tests/unit/test_core.py
  tests/unit/test_database_observer.py
Labels: Libraries: Out of sync, complex

#332 ci(digest): Add digest pinning
  renovate.json
Labels: Libraries: Out of sync, trivial
