Repository canonical/indico-operator, pull requests merged in 2024-09, with the labels that each got.

#450 feat: Update Charm to use Redis HA
  src/charm.py
  tests/unit/test_base.py
  tests/unit/test_core.py
  tox.ini
Labels: enhancement, good first issue, Libraries: OK, trivial

#452 ISD-2208 and ISD-2209: Update reference pages
  docs/reference/actions.md
  docs/reference/configurations.md
  docs/reference/integrations.md
Labels: documentation, Libraries: OK, trivial

#453 Switch to edge runners
  .github/workflows/test.yaml
Labels: Libraries: OK, trivial
