Repository canonical/indico-operator, pull requests merged in 2024-04, with the labels that each got.

#368 Split integration tests
  .github/workflows/integration_test.yaml
  tests/integration/conftest.py
  tests/integration/test_actions.py
  tests/integration/test_charm.py
  tests/integration/test_saml.py
Labels: Libraries: OK, trivial

#370 Update indico version to 3.3.1
  .github/workflows/test.yaml
  .licenserc.yaml
  docs/tutorial/getting-started.md
  indico_rock/plugins/__init__.py
  indico_rock/plugins/anonymize/setup.cfg
  indico_rock/plugins/autocreate/setup.cfg
  indico_rock/rockcraft.yaml
  nginx_rock/rockcraft.yaml
  src/charm.py
  tests/unit/pre_run_script.sh
  tests/unit/test_actions.py
  tox.ini
Labels: Libraries: Out of sync, urgent, complex

#373 Use s3 integrator
  .github/workflows/integration_test.yaml
  config.yaml
  docs/how-to/configure-s3.md
  lib/charms/data_platform_libs/v0/s3.py
  metadata.yaml
  pyproject.toml
  src-docs/charm.py.md
  src-docs/s3_observer.py.md
  src-docs/state.py.md
  src/charm.py
  src/s3_observer.py
  src/state.py
  tests/integration/conftest.py
  tests/integration/test_actions.py
  tests/integration/test_charm.py
  tests/integration/test_s3.py
  tests/integration/test_saml.py
  tests/unit/test_actions.py
  tests/unit/test_core.py
  tests/unit/test_s3_observer.py
  tests/unit/test_saml_observer.py
  tests/unit/test_smtp_observer.py
  tests/unit/test_state.py
Labels: Libraries: OK, trivial

#384 Increase nginx timeout to 300s
  nginx_rock/etc/nginx.conf
Labels: Libraries: OK, trivial

#385 Add external access docs
  docs/reference/external-access.md
Labels: Libraries: Out of sync, trivial

#387 Increase timeout for /api/events
  nginx_rock/etc/nginx.conf
Labels: Libraries: OK, trivial

#390 Add redeployment documentation
  docs/how-to/redeploy.md
Labels: Libraries: Out of sync, trivial
